# travis.yaml docs https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7

install: 
  - python setup.py install
  - pip install -r requirements_dev.txt --use-mirrors

script:
  - flake8 tests
  - flake8 domain_utils
  -	coverage run --source domain_utils -m pytest
  - coverage report -m
