# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - python setup.py install
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - flake8 tests
  - flake8 domain_utils
  -	coverage run --source domain_utils -m pytest
  - coverage report -m
