version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.5
      - test-3.6
      - test-3.7
      - test-3.8
jobs:
  test-3.5: &test-template
    docker:
      - image: cimg/base:2020.01
    environment:
      PYTHON_VERSION: 3.5
    steps:
      - checkout
      - run:
          name: Setup conda
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
            bash miniconda.sh -b -p $HOME/miniconda
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            echo ------ conda info
            conda info -a
            echo ------ setting up env
            conda create -q -n testenv python=$PYTHON_VERSION pip -c conda-forge
      - run:
          name: Setup package
          command: |
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda activate testenv
            python setup.py install
            pip install -r requirements_dev.txt
      - run:
          name: Run tests
          command: |
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda activate testenv
            flake8 tests
            flake8 domain_utils
            coverage run --source domain_utils -m pytest
            coverage report -m
  test-3.6:
    <<: *test-template
    environment:
      PYTHON_VERSION: 3.6
  test-3.7:
    <<: *test-template
    environment:
      PYTHON_VERSION: 3.7
  test-3.8:
    <<: *test-template
    environment:
      PYTHON_VERSION: 3.8
